version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: assmin@123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
   build: .
   container_name: fs_service
   restart: always
   depends_on:
     - postgres
   ports:
    - "3000:3000"
   environment:
     DATABASE_URL: postgresql://admin:assmin@123@postgres:5432/postgres?schema=public
   networks:
     - my_network

volumes:
  postgres_data:

networks:
  my_network: