version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: assmin@123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

#  app:
#    build: .
#    container_name: my_app
#    restart: always
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase
#    networks:
#      - my_network

volumes:
  postgres_data:

networks:
  my_network: